apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-cnee
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-go-rhtap-three-component-scenarios-cnee
    app.kubernetes.io/part-of: mc-three-scenarios
  name: devfile-go-rhtap-three-component-scenarios-cnee
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-cnee
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-go-rhtap-three-component-scenarios-cnee
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gzak-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-cnee@sha256:5f3f99dce7b33280b1705981423af26b57697cb47507c5d29424badd5a4c3f39
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
